# Поддержка мыши
set -g mouse on
# История прокрутки
set-option -g history-limit 1000
# Цвет активный вкладки
set-window-option -g window-status-current-style "bg=#aaaaaa fg=#eeeeee"
set-window-option -g window-status-style "bg=#aaaaaa fg=#eeeeee"


# Исправление работы tmux при подключении по ssh
# set -g default-terminal "xterm-256color"
set -g default-terminal "tmux-256color"
set-window-option -g xterm-keys on

# Pi
set -g extended-keys on
set -g extended-keys-format csi-u

# TPM
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# https://github.com/b0o/tmux-autoreload
set-option -g @plugin 'b0o/tmux-autoreload'

# https://github.com/lloydbond/tmux-floating-terminal
set -g @plugin 'lloydbond/tmux-floating-terminal'

set -g @floating_scratch_term 'M-i'
set -g @floating_scratch_to_active_win 'M-h'
set -g @floating_scratch_to_win 'M-l'
set -g @floating_active_pane_to_scratch 'M-m'

# https://github.com/sainnhe/tmux-fzf
set -g @plugin 'sainnhe/tmux-fzf'

TMUX_FZF_LAUNCH_KEY="C-f"

# https://github.com/tmux-plugins/tmux-logging
set -g @plugin 'tmux-plugins/tmux-logging'

# https://github.com/jaclu/tmux-menus
set -g @plugin 'jaclu/tmux-menus'

# https://github.com/tmux-plugins/tmux-sidebar
set -g @plugin 'tmux-plugins/tmux-sidebar'

# https://github.com/joshmedeski/tmux-nerd-font-window-name
set -g @plugin 'joshmedeski/tmux-nerd-font-window-name'

# https://github.com/rickstaa/tmux-notify
set -g @plugin 'rickstaa/tmux-notify'

# https://github.com/ofirgall/tmux-window-name
set -g @plugin 'ofirgall/tmux-window-name'

# https://github.com/AranBorkum/tmux-cookie-cutter
# set -g @plugin 'AranBorkum/tmux-cookie-cutter'

# https://github.com/Freed-Wu/tmux-digit
set -g @digit-style square
set -g @plugin Freed-Wu/tmux-digit

# https://github.com/jonmosco/kube-tmux
set -g @plugin 'jonmosco/kube-tmux'

# https://github.com/dracula/tmux
# set -g @plugin 'dracula/tmux'

run '~/.tmux/plugins/tpm/tpm'
